# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shubhamdemo"
client_id = "f45ab5c37973a3b5da7b8e100c21cac5"
application_url = "https://engineer-integration-interested-gmt.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://engineer-integration-interested-gmt.trycloudflare.com/auth/callback",
  "https://engineer-integration-interested-gmt.trycloudflare.com/auth/shopify/callback",
  "https://engineer-integration-interested-gmt.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-16aa2a8a.myshopify.com"
