# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "fridayDemo"
client_id = "38d612ed01571c61aa9a5fbc1f8bea14"
application_url = "https://texts-dv-mouse-drug.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://texts-dv-mouse-drug.trycloudflare.com/auth/callback",
  "https://texts-dv-mouse-drug.trycloudflare.com/auth/shopify/callback",
  "https://texts-dv-mouse-drug.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mueshiteststore.myshopify.com"
